version: "3"

services:
  app:
    container_name: socket.io-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      /bin/bash -c "
      npm run build && npm run start
      "